import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import * as E from '../dist/duel-engine.mjs';
import {KEEPERS} from '../dist/market-art.mjs';
const elements=new Map();
function element(id){if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',hidden:false,getContext:()=>({}),querySelectorAll:()=>[],showModal(){this.open=true;},close(){this.open=false;}});return elements.get(id);}
const saved=new Map(),context={E,KEEPERS,itemURL:()=>'',document:{getElementById:element},localStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v),removeItem:k=>saved.delete(k)},structuredClone,performance:{now:()=>0},matchMedia:()=>({matches:true}),setTimeout:fn=>{queueMicrotask(fn);},console};
let source=fs.readFileSync(new URL('../dist/duel.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'');source=source.slice(0,source.indexOf('try{[art,town,market]'))+'\nglobalThis.ui={get run(){return run},get view(){return view},get training(){return training},get category(){return category},get shopSlot(){return shopSlot},get preview(){return preview},arrive(){const done=townTravel?.done;townTravel=null;locked=false;done?.();},previewRun,render,go};render();';
vm.runInNewContext(source,context);
const click=async action=>{element('screen').onclick({target:{closest:()=>({dataset:{do:action},disabled:false})}});for(let i=0;i<10;i++)await Promise.resolve();};
assert.match(element('screen').innerHTML,/Who will claim/);await click('choose:dwarf');assert.equal(context.ui.view,'town');assert.match(element('screen').innerHTML,/Weaponsmith/);await click('offer');assert.equal(context.ui.view,'offer');await click('fight');assert.equal(context.ui.view,'fight');const b=context.ui.run.battle;await click('act:jump');assert.equal(b.turn,'p');assert.equal(b.count,3);assert(E.load(saved.get(E.SAVE)));
E.surrender(context.ui.run,{});context.ui.go('town');context.ui.run.gold=200;await click('shop:magic');context.ui.arrive();await click('preview:sleep');await click('buy');assert(context.ui.run.spells.includes('sleep'));await click('preview:lightning');await click('train');assert(context.ui.training);assert(context.ui.training.spells.includes('lightning'));await click('leave-training');assert.equal(context.ui.training,null);assert(!context.ui.run.spells.includes('lightning'));
context.ui.go('town');assert.match(element('screen').innerHTML,/NEXT PRIZE/);assert.match(element('screen').innerHTML,/Ironbark axe/);await click('shop:weapons');context.ui.arrive();assert.equal((element('screen').innerHTML.match(/class="stock-item /g)||[]).length,8);context.ui.run.gold=500;await click('preview:melee:3');assert.equal(context.ui.previewRun().gear.melee,3);assert.equal(context.ui.run.gear.melee,0);await click('goal');assert.deepEqual(context.ui.run.goal,{category:'weapons',id:'melee:3'});assert(E.load(saved.get(E.SAVE)).goal);context.ui.go('town');assert.match(element('screen').innerHTML,/YOUR GOAL/);assert.match(element('screen').innerHTML,/claim the First Crown/);await click('goal-shop');context.ui.arrive();assert.equal(context.ui.category,'weapons');assert.equal(context.ui.shopSlot,'melee');assert.equal(context.ui.preview,'melee:3');await click('preview:melee:1');await click('goal');await click('buy');assert.equal(context.ui.run.gear.melee,1);assert.equal(context.ui.run.goal,null);assert.equal(context.ui.preview,'melee:2');await click('preview:melee:0');assert.equal(context.ui.previewRun().gear.melee,0);await click('equipped');assert.equal(context.ui.previewRun().gear.melee,1);await click('slot:ranged');assert.match(element('screen').innerHTML,/throwing axe/);
E.setGoal(context.ui.run,'weapons','melee:3');context.ui.run.result={won:true,gold:47,master:false,dead:false,name:'Test'};context.ui.go('result');assert.match(element('screen').innerHTML,/YOUR GOAL/);assert.match(element('screen').innerHTML,/claim the First Crown/);context.ui.run.result=null;context.ui.run.level=3;context.ui.run.points=1;await click('tournament');assert.equal(context.ui.view,'attributes');await click('stat:strength');await click('tournament');assert(element('confirm').open);element('confirm-yes').onclick();assert.equal(context.ui.view,'tournament');assert(context.ui.run.tournament);console.log('Turn-based UI handlers: town, opponent, action/AI reply, save, shop goals, practice and tournament passed (mock DOM).');
