import assert from 'node:assert/strict';
import {newRun,act,unavailable,enemyPlan,distance,migrate,reward,buy,next,tributeValue,FOES,BASIC} from '../dist/engine.mjs';
const close=()=>{const s=newRun();s.enemyPos=3;return s;};
let s=newRun(),events=[];assert.equal(unavailable(s,'attack'),'Need range 1');const snap=structuredClone(s);assert.equal(act(s,'attack'),false);assert.deepEqual(s,snap);assert.deepEqual(enemyPlan(s),['approach',2]);act(s,'forward',events);assert.equal(s.playerPos,4);assert.equal(s.energy,4);assert.equal(s.hp,64);assert.equal(events[1].type,'move');assert.equal(events[1].to,4);
s=close();events=[];act(s,'back',events);assert.equal(s.playerPos,0);assert.equal(s.hp,72);assert.equal(s.enemyPos,1);assert.equal(unavailable(s,'back'),'Arena wall');assert.ok(events.some(e=>e.type==='move'&&e.actor==='enemy'));
s=close();act(s,'guard');assert.equal(s.hp,72);assert.equal(s.turn,1);assert.equal(s.bonus,3);s=close();s.bonus=4;act(s,'guard');assert.equal(s.bonus,4);s=close();s.round=3;s.foeHp=62;act(s,'guard');assert.equal(s.bonus,0);assert.equal(s.hp,70);
s=close();s.round=3;s.foeHp=62;events=[];act(s,'dodge',events);assert.equal(s.hp,65);assert.equal(s.energy,3);assert.equal(events.filter(e=>e.type==='evade').length,1);assert.equal(events.filter(e=>e.type==='hit'&&e.actor==='enemy').length,1);assert.equal(act(s,'dodge'),false);
s=close();s.energy=0;assert.equal(act(s,'power'),false);act(s,'rest');assert.equal(s.energy,3);assert.equal(s.hp,64);
s=newRun();s.moves=['venom'];events=[];act(s,'venom',events);assert.ok(s.foeHp<44);assert.equal(s.hp,72);assert.equal(s.enemyPos,3);
s=close();s.foeHp=1;events=[];act(s,'attack',events);assert.equal(events.at(-1).type,'defeat');assert.equal(events.some(e=>e.actor==='enemy'&&e.type==='hit'),false);
s=close();s.moves=['riposte'];act(s,'riposte');const turn=s.turn;assert.equal(act(s,'riposte'),false);assert.equal(s.turn,turn);act(s,'guard');act(s,'guard');assert.equal(act(s,'riposte'),true);
s=close();s.stage='reward';s.moves=['heavy','drain','brace'];assert.equal(reward(s,'move'),false);assert.equal(reward(s,'move','heavy'),true);assert.equal(reward(s,'gold'),false);assert.equal(buy(s,'weapon'),false);next(s);assert.equal(s.round,1);assert.equal(s.foeHp,53);assert.equal(s.energy,6);assert.equal(distance(s),3);
s=newRun();delete s.energy;delete s.playerPos;delete s.enemyPos;migrate(s);assert.equal(s.energy,6);assert.equal(distance(s),3);
const tovin=newRun('Tovin','tovin'),suri=newRun('Suri','suri');assert.equal(tovin.maxHp,84);assert.equal(tovin.armor,1);assert.equal(suri.maxHp,64);assert.equal(suri.weapon,1);suri.enemyPos=4;assert.equal(unavailable(suri,'attack'),'');assert.equal(tributeValue(suri),30);
let seed=8147;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};let wins=0,best=0;
for(let run=0;run<300;run++){s=newRun();for(let i=0;i<400&&!['won','lost'].includes(s.stage);i++){if(s.stage==='battle'){const choices=[...Object.keys(BASIC),...s.moves].filter(a=>!unavailable(s,a)).map(a=>{const x=structuredClone(s);act(x,a);const score=(s.foeHp-x.foeHp)*1.2+(x.hp-s.hp)*1.5+(x.energy-s.energy)*1.2+(x.bonus-s.bonus)*.3+(distance(s)-distance(x))*2+(x.stage==='reward'||x.stage==='won'?100:0)+random()*12;return {a,score};}).sort((a,b)=>b.score-a.score);assert.ok(choices.length);act(s,choices[0].a);}else if(s.stage==='reward'){if(s.moves.length<3)reward(s,'move');else reward(s,run%3?'gold':'gear');}else{if(s.hp<42&&s.gold>=20)buy(s,'heal');else if(s.gold>=30)buy(s,run%2?'armor':'weapon');else next(s);}assert.ok(s.playerPos>=0&&s.playerPos<s.enemyPos&&s.enemyPos<=8);assert.ok(s.energy>=0&&s.energy<=6);assert.ok(s.hp>=0&&s.hp<=72);assert.ok(s.foeHp>=0&&s.foeHp<=FOES[s.round].hp);assert.ok(s.gold>=0);best=Math.max(best,s.round);}if(s.stage==='won')wins++;}
console.log({simulations:300,wins,bestGate:best+1});assert.ok(wins>0,'Must be possible to complete tournament');console.log('Range, movement, walls, enemy pursuit, energy, dodge, cooldowns, reward and save migration checks passed.');
