import assert from 'node:assert/strict';
import {Skeleton,POSES,rigMarkup} from '../dist/rig.js';
let pending=new Map(),id=0;
globalThis.requestAnimationFrame=fn=>{pending.set(++id,fn);return id};
globalThis.cancelAnimationFrame=n=>pending.delete(n);
const joints=Object.keys(POSES.idle).map(key=>({dataset:{joint:key},style:{}}));
const body={style:{}};
const root={querySelectorAll:()=>joints,querySelector:()=>body};
const rig=new Skeleton(root);
rig.pose('strike',120);rig.tick(rig.started+120);
for(const j of joints)assert.equal(j.style.transform,`rotate(${POSES.strike[j.dataset.joint]}deg)`);
rig.walk(true);rig.tick(rig.started+150);
assert.notEqual(joints.find(j=>j.dataset.joint==='leg').style.transform,joints.find(j=>j.dataset.joint==='backLeg').style.transform);
rig.walk(false);rig.pose('block',100);rig.tick(rig.started+100);
assert.equal(joints.find(j=>j.dataset.joint==='backArm').style.transform,'rotate(-68deg)');
rig.destroy();const before=pending.size;rig.tick(performance.now());assert.equal(pending.size,before);
for(const pose of Object.values(POSES))assert.deepEqual(Object.keys(pose),Object.keys(POSES.idle));
assert.ok(rigMarkup().includes('part-sword'));assert.ok(rigMarkup().includes('part-shield'));
console.log('Skeleton poses, independent walking joints, shield pose and animation teardown passed.');
